spring.application.name=spring_kadai_form
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_db_kadai
spring.datasource.username=postgres
spring.datasource.password=J20239rs
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update